<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'floraqueen\\modules\\basket\\basket' => '/modules/Basket/Basket.php',
                'floraqueen\\modules\\basket\\voucheralreadyaddedexception' => '/modules/Basket/VoucherAlreadyAddedException.php',
                'floraqueen\\modules\\product\\product' => '/modules/Product/Product.php',
                'floraqueen\\modules\\product\\producta' => '/modules/Product/ProductA.php',
                'floraqueen\\modules\\product\\productb' => '/modules/Product/ProductB.php',
                'floraqueen\\modules\\product\\productc' => '/modules/Product/ProductC.php',
                'floraqueen\\modules\\product\\productinterface' => '/modules/Product/ProductInterface.php',
                'floraqueen\\modules\\product\\voucher' => '/modules/Voucher/Voucher.php',
                'floraqueen\\modules\\product\\voucherr' => '/modules/Voucher/VoucherR.php',
                'floraqueen\\modules\\product\\vouchers' => '/modules/Voucher/VoucherS.php',
                'floraqueen\\modules\\product\\voucherv' => '/modules/Voucher/VoucherV.php',
                'floraqueen\\modules\\voucher\\voucherinterface' => '/modules/Voucher/VoucherInterface.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd
